### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by ghostknow** [ShaMan123/react-native-scroll-view#2]
When I pinch to zoom, it's nothing happen. Do I need to setup typescript?

**Comment by marstall** [comment]
was able to get it working with the following steps:
- modify _responders to return {true} for the following two methods:
```            onStartShouldSetResponderCapture: () => true,
            onMoveShouldSetResponderCapture: () => true,
```
- pass pinchGestureEnabled={true}
- pass explicit minimumZoomScale and maximumZoomScales; they both default to 1 which effectively disables zoom.

**Comment by ghostknow** [comment]
> * pinchGestureEnabled

can u post your sample code for me? thanks

**Comment by ShaMan123** [comment]
Archiving the repo.
There are better options out there.
I suggest you take a look at [RNGH](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html)
