### ISSUE TITLE
needed to set onStartShouldSetResponderCapture to true to get it working for me

### ISSUE THREAD

**Issue by marstall** [ShaMan123/react-native-scroll-view#3]
(never mind, this doesn't seem to be the case)

**Comment by ShaMan123** [comment]
Archiving the repo.
There are better options out there.
I suggest you take a look at [RNGH](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html)

**Comment by marstall** [comment]
thanks - we ended up rolling our own - but learned a lot from your repo. appreciate your work. (that link doesn't work for me btw)
